#include "mpiabi_function_pointers_fortran.h"

// A.3 C Bindings

// A.3.1 Point-to-Point Communication C Bindings

void (*mpiabi_bsend_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_bsend_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_bsend_init_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_bsend_init_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_buffer_attach_ptr)(void *buffer, MPIABI_Fint *size, MPIABI_Fint *ierror);
// void (*mpiabi_buffer_attach_c_ptr)(void *buffer, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_buffer_detach_ptr)(void *buffer_addr, MPIABI_Fint *size, MPIABI_Fint *ierror);
// void (*mpiabi_buffer_detach_c_ptr)(void *buffer_addr, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_buffer_flush_ptr)(MPIABI_Fint *ierror);
void (*mpiabi_buffer_iflush_ptr)(MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_cancel_ptr)(MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_comm_attach_buffer_ptr)(MPIABI_Fint *comm, void *buffer, MPIABI_Fint *size, MPIABI_Fint *ierror);
// void (*mpiabi_comm_attach_buffer_c_ptr)(MPIABI_Fint *comm, void *buffer, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_comm_detach_buffer_ptr)(MPIABI_Fint *comm, void *buffer_addr, MPIABI_Fint *size, MPIABI_Fint *ierror);
// void (*mpiabi_comm_detach_buffer_c_ptr)(MPIABI_Fint *comm, void *buffer_addr, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_comm_flush_buffer_ptr)(MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_comm_iflush_buffer_ptr)(MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_get_count_ptr)(const MPIABI_Fint *status, MPIABI_Fint *datatype, MPIABI_Fint *count, MPIABI_Fint *ierror);
// void (*mpiabi_get_count_c_ptr)(const MPIABI_Fint *status, MPIABI_Fint *datatype, MPIABI_Count *count, MPIABI_Fint *ierror);
void (*mpiabi_ibsend_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ibsend_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_improbe_ptr)(MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *flag, MPIABI_Fint *message, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_imrecv_ptr)(void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *message, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_imrecv_c_ptr)(void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *message, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_iprobe_ptr)(MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *flag, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_irecv_ptr)(void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_irecv_c_ptr)(void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_irsend_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_irsend_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_isend_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_isend_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_isendrecv_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, MPIABI_Fint *dest, MPIABI_Fint *sendtag, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *source, MPIABI_Fint *recvtag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_isendrecv_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, MPIABI_Fint *dest, MPIABI_Fint *sendtag, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *source, MPIABI_Fint *recvtag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_isendrecv_replace_ptr)(void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *sendtag, MPIABI_Fint *source, MPIABI_Fint *recvtag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_isendrecv_replace_c_ptr)( void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *sendtag, MPIABI_Fint *source, MPIABI_Fint *recvtag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_issend_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_issend_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_mprobe_ptr)(MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *message, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_mrecv_ptr)(void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *message, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_mrecv_c_ptr)(void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *message, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_probe_ptr)(MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_recv_ptr)(void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_recv_c_ptr)(void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_recv_init_ptr)(void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_recv_init_c_ptr)(void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_request_free_ptr)(MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_request_get_status_ptr)(MPIABI_Fint *request, MPIABI_Fint *flag, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_request_get_status_all_ptr)( MPIABI_Fint *count, const MPIABI_Fint *array_of_requests[], MPIABI_Fint *flag, MPIABI_Fint *array_of_statuses[], MPIABI_Fint *ierror);
void (*mpiabi_request_get_status_any_ptr)( MPIABI_Fint *count, const MPIABI_Fint *array_of_requests[], MPIABI_Fint *index, MPIABI_Fint *flag, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_request_get_status_some_ptr)( MPIABI_Fint *incount, const MPIABI_Fint *array_of_requests[], MPIABI_Fint *outcount, MPIABI_Fint *array_of_indices[], MPIABI_Fint *array_of_statuses[], MPIABI_Fint *ierror);
void (*mpiabi_rsend_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_rsend_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_rsend_init_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_rsend_init_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_send_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_send_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_send_init_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_send_init_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_sendrecv_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, MPIABI_Fint *dest, MPIABI_Fint *sendtag, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *source, MPIABI_Fint *recvtag, MPIABI_Fint *comm, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_sendrecv_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, MPIABI_Fint *dest, MPIABI_Fint *sendtag, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *source, MPIABI_Fint *recvtag, MPIABI_Fint *comm, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_sendrecv_replace_ptr)(void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *sendtag, MPIABI_Fint *source, MPIABI_Fint *recvtag, MPIABI_Fint *comm, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_sendrecv_replace_c_ptr)(void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *sendtag, MPIABI_Fint *source, MPIABI_Fint *recvtag, MPIABI_Fint *comm, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_session_attach_buffer_ptr)(MPIABI_Fint *session, void *buffer, MPIABI_Fint *size, MPIABI_Fint *ierror);
// void (*mpiabi_session_attach_buffer_c_ptr)(MPIABI_Fint *session, void *buffer, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_session_detach_buffer_ptr)(MPIABI_Fint *session, void *buffer_addr, MPIABI_Fint *size, MPIABI_Fint *ierror);
// void (*mpiabi_session_detach_buffer_c_ptr)(MPIABI_Fint *session, void *buffer_addr, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_session_flush_buffer_ptr)(MPIABI_Fint *session, MPIABI_Fint *ierror);
void (*mpiabi_session_iflush_buffer_ptr)(MPIABI_Fint *session, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ssend_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_ssend_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_ssend_init_ptr)(const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ssend_init_c_ptr)(const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_start_ptr)(MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_startall_ptr)(MPIABI_Fint *count, MPIABI_Fint *array_of_requests[], MPIABI_Fint *ierror);
void (*mpiabi_status_get_error_ptr)(MPIABI_Fint *status, MPIABI_Fint *err, MPIABI_Fint *ierror);
void (*mpiabi_status_get_source_ptr)(MPIABI_Fint *status, MPIABI_Fint *source, MPIABI_Fint *ierror);
void (*mpiabi_status_get_tag_ptr)(MPIABI_Fint *status, MPIABI_Fint *tag, MPIABI_Fint *ierror);
void (*mpiabi_test_ptr)(MPIABI_Fint *request, MPIABI_Fint *flag, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_test_cancelled_ptr)(const MPIABI_Fint *status, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_testall_ptr)(MPIABI_Fint *count, MPIABI_Fint *array_of_requests[], MPIABI_Fint *flag, MPIABI_Fint *array_of_statuses[], MPIABI_Fint *ierror);
void (*mpiabi_testany_ptr)(MPIABI_Fint *count, MPIABI_Fint *array_of_requests[], MPIABI_Fint *index, MPIABI_Fint *flag, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_testsome_ptr)(MPIABI_Fint *incount, MPIABI_Fint *array_of_requests[], MPIABI_Fint *outcount, MPIABI_Fint *array_of_indices[], MPIABI_Fint *array_of_statuses[], MPIABI_Fint *ierror);
void (*mpiabi_wait_ptr)(MPIABI_Fint *request, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_waitall_ptr)(MPIABI_Fint *count, MPIABI_Fint *array_of_requests[], MPIABI_Fint *array_of_statuses[], MPIABI_Fint *ierror);
void (*mpiabi_waitany_ptr)(MPIABI_Fint *count, MPIABI_Fint *array_of_requests[], MPIABI_Fint *index, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_waitsome_ptr)(MPIABI_Fint *incount, MPIABI_Fint *array_of_requests[], MPIABI_Fint *outcount, MPIABI_Fint *array_of_indices[], MPIABI_Fint *array_of_statuses[], MPIABI_Fint *ierror);

// A.3.2 Partitioned Communication C Bindings

void (*mpiabi_parrived_ptr)(MPIABI_Fint *request, MPIABI_Fint *partition, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_pready_ptr)(MPIABI_Fint *partition, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_pready_list_ptr)(MPIABI_Fint *length, const MPIABI_Fint *array_of_partitions[], MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_pready_range_ptr)(MPIABI_Fint *partition_low, MPIABI_Fint *partition_high, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_precv_init_ptr)(void *buf, MPIABI_Fint *partitions, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *source, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_psend_init_ptr)(const void *buf, MPIABI_Fint *partitions, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *dest, MPIABI_Fint *tag, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);

// A.3.3 Datatypes C Bindings

MPI_Aint (*mpiabi_aint_add_ptr)(MPIABI_Aint *base, MPIABI_Aint *disp);
MPI_Aint (*mpiabi_aint_diff_ptr)(MPIABI_Aint *addr1, MPIABI_Aint *addr2);
void (*mpiabi_get_address_ptr)(const void *location, MPIABI_Aint *address, MPIABI_Fint *ierror);
void (*mpiabi_get_elements_ptr)(const MPIABI_Fint *status, MPIABI_Fint *datatype, MPIABI_Fint *count, MPIABI_Fint *ierror);
// void (*mpiabi_get_elements_c_ptr)(const MPIABI_Fint *status, MPIABI_Fint *datatype, MPIABI_Count *count, MPIABI_Fint *ierror);
void (*mpiabi_pack_ptr)(const void *inbuf, MPIABI_Fint *incount, MPIABI_Fint *datatype, void *outbuf, MPIABI_Fint *outsize, MPIABI_Fint *position, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_pack_c_ptr)(const void *inbuf, MPIABI_Count *incount, MPIABI_Fint *datatype, void *outbuf, MPIABI_Count *outsize, MPIABI_Count *position, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_pack_external_ptr)(const char datarep[], const void *inbuf, MPIABI_Fint *incount, MPIABI_Fint *datatype, void *outbuf, MPIABI_Aint *outsize, MPIABI_Aint *position, MPIABI_Fint *ierror);
// void (*mpiabi_pack_external_c_ptr)(const char datarep[], const void *inbuf, MPIABI_Count *incount, MPIABI_Fint *datatype, void *outbuf, MPIABI_Count *outsize, MPIABI_Count *position, MPIABI_Fint *ierror);
void (*mpiabi_pack_external_size_ptr)(const char datarep[], MPIABI_Count *incount, MPIABI_Fint *datatype, MPIABI_Aint *size, MPIABI_Fint *ierror);
// void (*mpiabi_pack_external_size_c_ptr)(const char datarep[], MPIABI_Count *incount, MPIABI_Fint *datatype, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_pack_size_ptr)(MPIABI_Fint *incount, MPIABI_Fint *datatype, MPIABI_Fint *comm, MPIABI_Fint *size, MPIABI_Fint *ierror);
// void (*mpiabi_pack_size_c_ptr)(MPIABI_Count *incount, MPIABI_Fint *datatype, MPIABI_Fint *comm, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_type_commit_ptr)(MPIABI_Fint *datatype, MPIABI_Fint *ierror);
void (*mpiabi_type_contiguous_ptr)(MPIABI_Fint *count, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_contiguous_c_ptr)(MPIABI_Count *count, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_create_darray_ptr)( MPIABI_Fint *size, MPIABI_Fint *rank, MPIABI_Fint *ndims, const MPIABI_Fint *array_of_gsizes[], const MPIABI_Fint *array_of_distribs[], const MPIABI_Fint *array_of_dargs[], const MPIABI_Fint *array_of_psizes[], MPIABI_Fint *order, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_create_darray_c_ptr)( MPIABI_Fint *size, MPIABI_Fint *rank, MPIABI_Fint *ndims, const MPIABI_Count *array_of_gsizes[], const MPIABI_Fint *array_of_distribs[], const MPIABI_Fint *array_of_dargs[], const MPIABI_Fint *array_of_psizes[], MPIABI_Fint *order, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_create_hindexed_ptr)( MPIABI_Fint *count, const MPIABI_Fint *array_of_blocklengths[], const MPIABI_Aint *array_of_displacements[], MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_create_hindexed_block_ptr)( MPIABI_Fint *count, MPIABI_Fint *blocklength, const MPIABI_Aint *array_of_displacements[], MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_create_hindexed_block_c_ptr)( MPIABI_Count *count, MPIABI_Count *blocklength, const MPIABI_Count *array_of_displacements[], MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_create_hindexed_c_ptr)( MPIABI_Count *count, const MPIABI_Count *array_of_blocklengths[], const MPIABI_Count *array_of_displacements[], MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_create_hvector_ptr)( MPIABI_Fint *count, MPIABI_Fint *blocklength, MPIABI_Aint *stride, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_create_hvector_c_ptr)( MPIABI_Count *count, MPIABI_Count *blocklength, MPIABI_Count *stride, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_create_indexed_block_ptr)( MPIABI_Fint *count, MPIABI_Fint *blocklength, const MPIABI_Fint *array_of_displacements[], MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_create_indexed_block_c_ptr)( MPIABI_Count *count, MPIABI_Count *blocklength, const MPIABI_Count *array_of_displacements[], MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_create_resized_ptr)(MPIABI_Fint *oldtype, MPIABI_Aint *lb, MPIABI_Aint *extent, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_create_resized_c_ptr)(MPIABI_Fint *oldtype, MPIABI_Count *lb, MPIABI_Count *extent, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_create_struct_ptr)( MPIABI_Fint *count, const MPIABI_Fint *array_of_blocklengths[], const MPIABI_Aint *array_of_displacements[], const MPIABI_Fint *array_of_types[], MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_create_struct_c_ptr)( MPIABI_Count *count, const MPIABI_Count *array_of_blocklengths[], const MPIABI_Count *array_of_displacements[], const MPIABI_Fint *array_of_types[], MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_create_subarray_ptr)( MPIABI_Fint *ndims, const MPIABI_Fint *array_of_sizes[], const MPIABI_Fint *array_of_subsizes[], const MPIABI_Fint *array_of_starts[], MPIABI_Fint *order, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_create_subarray_c_ptr)( MPIABI_Fint *ndims, const MPIABI_Count *array_of_sizes[], const MPIABI_Count *array_of_subsizes[], const MPIABI_Count *array_of_starts[], MPIABI_Fint *order, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_dup_ptr)(MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_free_ptr)(MPIABI_Fint *datatype, MPIABI_Fint *ierror);
void (*mpiabi_type_get_contents_ptr)( MPIABI_Fint *datatype, MPIABI_Fint *max_integers, MPIABI_Fint *max_addresses, MPIABI_Fint *max_datatypes, MPIABI_Fint *array_of_integers[], MPIABI_Aint *array_of_addresses[], MPIABI_Fint *array_of_datatypes[], MPIABI_Fint *ierror);
// void (*mpiabi_type_get_contents_c_ptr)( MPIABI_Fint *datatype, MPIABI_Count *max_integers, MPIABI_Count *max_addresses, MPIABI_Count *max_large_counts, MPIABI_Count *max_datatypes, MPIABI_Fint *array_of_integers[], MPIABI_Aint *array_of_addresses[], MPIABI_Count *array_of_large_counts[], MPIABI_Fint *array_of_datatypes[], MPIABI_Fint *ierror);
void (*mpiabi_type_get_envelope_ptr)(MPIABI_Fint *datatype, MPIABI_Fint *num_integers, MPIABI_Fint *num_addresses, MPIABI_Fint *num_datatypes, MPIABI_Fint *combiner, MPIABI_Fint *ierror);
// void (*mpiabi_type_get_envelope_c_ptr)( MPIABI_Fint *datatype, MPIABI_Count *num_integers, MPIABI_Count *num_addresses, MPIABI_Count *num_large_counts, MPIABI_Count *num_datatypes, MPIABI_Fint *combiner, MPIABI_Fint *ierror);
void (*mpiabi_type_get_extent_ptr)(MPIABI_Fint *datatype, MPIABI_Aint *lb, MPIABI_Aint *extent, MPIABI_Fint *ierror);
// void (*mpiabi_type_get_extent_c_ptr)(MPIABI_Fint *datatype, MPIABI_Count *lb, MPIABI_Count *extent, MPIABI_Fint *ierror);
void (*mpiabi_type_get_true_extent_ptr)(MPIABI_Fint *datatype, MPIABI_Aint *true_lb, MPIABI_Aint *true_extent, MPIABI_Fint *ierror);
// void (*mpiabi_type_get_true_extent_c_ptr)(MPIABI_Fint *datatype, MPIABI_Count *true_lb, MPIABI_Count *true_extent, MPIABI_Fint *ierror);
void (*mpiabi_type_indexed_ptr)(MPIABI_Fint *count, const MPIABI_Fint *array_of_blocklengths[], const MPIABI_Fint *array_of_displacements[], MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_indexed_c_ptr)(MPIABI_Count *count, const MPIABI_Count *array_of_blocklengths[], const MPIABI_Count *array_of_displacements[], MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_size_ptr)(MPIABI_Fint *datatype, MPIABI_Fint *size, MPIABI_Fint *ierror);
// void (*mpiabi_type_size_c_ptr)(MPIABI_Fint *datatype, MPIABI_Count *size, MPIABI_Fint *ierror);
void (*mpiabi_type_vector_ptr)(MPIABI_Fint *count, MPIABI_Fint *blocklength, MPIABI_Fint *stride, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
// void (*mpiabi_type_vector_c_ptr)(MPIABI_Count *count, MPIABI_Count *blocklength, MPIABI_Count *stride, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_unpack_ptr)(const void *inbuf, MPIABI_Fint *insize, MPIABI_Fint *position, void *outbuf, MPIABI_Fint *outcount, MPIABI_Fint *datatype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_unpack_c_ptr)(const void *inbuf, MPIABI_Count *insize, MPIABI_Count *position, void *outbuf, MPIABI_Count *outcount, MPIABI_Fint *datatype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_unpack_external_ptr)(const char datarep[], const void *inbuf, MPIABI_Aint *insize, MPIABI_Aint *position, void *outbuf, MPIABI_Fint *outcount, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_unpack_external_c_ptr)(const char datarep[], const void *inbuf, MPIABI_Count *insize, MPIABI_Count *position, void *outbuf, MPIABI_Count *outcount, MPIABI_Fint *datatype, MPIABI_Fint *ierror);

// A.3.4 Collective Communication C Bindings

void (*mpiabi_allgather_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_allgather_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_allgather_init_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_allgather_init_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_allgatherv_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_allgatherv_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_allgatherv_init_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_allgatherv_init_c_ptr)( const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_allreduce_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_allreduce_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_allreduce_init_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_allreduce_init_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_alltoall_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_alltoall_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_alltoall_init_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_alltoall_init_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_alltoallv_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_alltoallv_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_alltoallv_init_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_alltoallv_init_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_alltoallw_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_alltoallw_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_alltoallw_init_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_alltoallw_init_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_barrier_ptr)(MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_barrier_init_ptr)(MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_bcast_ptr)(void *buffer, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_bcast_c_ptr)(void *buffer, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_bcast_init_ptr)(void *buffer, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_bcast_init_c_ptr)(void *buffer, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_exscan_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_exscan_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_exscan_init_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_exscan_init_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_gather_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_gather_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_gather_init_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_gather_init_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_gatherv_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_gatherv_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_gatherv_init_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_gatherv_init_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_iallgather_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_iallgather_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_iallgatherv_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_iallgatherv_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_iallreduce_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_iallreduce_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ialltoall_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ialltoall_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ialltoallv_ptr)(const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ialltoallv_c_ptr)(const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ialltoallw_ptr)(const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ialltoallw_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ibarrier_ptr)(MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ibcast_ptr)(void *buffer, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ibcast_c_ptr)(void *buffer, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_iexscan_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_iexscan_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_igather_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_igather_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_igatherv_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_igatherv_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ireduce_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ireduce_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ireduce_scatter_ptr)(const void *sendbuf, void *recvbuf, const MPIABI_Fint *recvcounts[], MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ireduce_scatter_block_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ireduce_scatter_block_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ireduce_scatter_c_ptr)(const void *sendbuf, void *recvbuf, const MPIABI_Count *recvcounts[], MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_iscan_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_iscan_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_iscatter_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_iscatter_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_iscatterv_ptr)(const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_iscatterv_c_ptr)(const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_op_commutative_ptr)(MPIABI_Fint *op, MPIABI_Fint *commute, MPIABI_Fint *ierror);
void (*mpiabi_op_create_ptr)(void (*user_fn)(void), MPIABI_Fint *commute, MPIABI_Fint *op, MPIABI_Fint *ierror);
// void (*mpiabi_op_create_c_ptr)(void (*user_fn)(void), MPIABI_Fint *commute, MPIABI_Fint *op, MPIABI_Fint *ierror);
void (*mpiabi_op_free_ptr)(MPIABI_Fint *op, MPIABI_Fint *ierror);
void (*mpiabi_reduce_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_reduce_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_reduce_init_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_reduce_init_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_reduce_local_ptr)(const void *inbuf, void *inoutbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *ierror);
// void (*mpiabi_reduce_local_c_ptr)(const void *inbuf, void *inoutbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *ierror);
void (*mpiabi_reduce_scatter_ptr)(const void *sendbuf, void *recvbuf, const MPIABI_Fint *recvcounts[], MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_reduce_scatter_block_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_reduce_scatter_block_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_reduce_scatter_block_init_ptr)( const void *sendbuf, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_reduce_scatter_block_init_c_ptr)( const void *sendbuf, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_reduce_scatter_c_ptr)(const void *sendbuf, void *recvbuf, const MPIABI_Count *recvcounts[], MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_reduce_scatter_init_ptr)(const void *sendbuf, void *recvbuf, const MPIABI_Fint *recvcounts[], MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_reduce_scatter_init_c_ptr)(const void *sendbuf, void *recvbuf, const MPIABI_Count *recvcounts[], MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_scan_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_scan_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_scan_init_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_scan_init_c_ptr)(const void *sendbuf, void *recvbuf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *op, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_scatter_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_scatter_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_scatter_init_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_scatter_init_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_scatterv_ptr)(const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_scatterv_c_ptr)(const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_scatterv_init_ptr)(const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_scatterv_init_c_ptr)(const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_type_get_value_index_ptr)(MPIABI_Fint *value_type, MPIABI_Fint *index_type, MPIABI_Fint *pair_type, MPIABI_Fint *ierror);

// A.3.5 Groups, Contexts, Communicators, and Caching C Bindings

void (*mpiabi_comm_compare_ptr)(MPIABI_Fint *comm1, MPIABI_Fint *comm2, MPIABI_Fint *result, MPIABI_Fint *ierror);
void (*mpiabi_comm_create_ptr)(MPIABI_Fint *comm, MPIABI_Fint *group, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_create_from_group_ptr)( MPIABI_Fint *group, const char *stringtag, MPIABI_Fint *info, MPI_Fint *errhandler, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_create_group_ptr)(MPIABI_Fint *comm, MPIABI_Fint *group, MPIABI_Fint *tag, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_create_keyval_ptr)(void (*comm_copy_attr_fn)(void), void (*comm_delete_attr_fn)(void), MPIABI_Fint *comm_keyval, void *extra_state, MPIABI_Fint *ierror);
void (*mpiabi_comm_delete_attr_ptr)(MPIABI_Fint *comm, MPIABI_Fint *comm_keyval, MPIABI_Fint *ierror);
void (*mpiabi_comm_dup_ptr)(MPIABI_Fint *comm, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_dup_with_info_ptr)(MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_free_ptr)(MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_comm_get_name_ptr)(MPIABI_Fint *comm, char *comm_name, MPIABI_Fint *resultlen, MPIABI_Fint *ierror);
void (*mpiabi_comm_free_keyval_ptr)(MPIABI_Fint *comm_keyval, MPIABI_Fint *ierror);
void (*mpiabi_comm_get_attr_ptr)(MPIABI_Fint *comm, MPIABI_Fint *comm_keyval, void *attribute_val, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_comm_get_info_ptr)(MPIABI_Fint *comm, MPIABI_Fint *info_used, MPIABI_Fint *ierror);
void (*mpiabi_comm_group_ptr)(MPIABI_Fint *comm, MPIABI_Fint *group, MPIABI_Fint *ierror);
void (*mpiabi_comm_idup_ptr)(MPIABI_Fint *comm, MPIABI_Fint *newcomm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_comm_idup_with_info_ptr)(MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *newcomm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_comm_rank_ptr)(MPIABI_Fint *comm, MPIABI_Fint *rank, MPIABI_Fint *ierror);
void (*mpiabi_comm_remote_group_ptr)(MPIABI_Fint *comm, MPIABI_Fint *group, MPIABI_Fint *ierror);
void (*mpiabi_comm_remote_size_ptr)(MPIABI_Fint *comm, MPIABI_Fint *size, MPIABI_Fint *ierror);
void (*mpiabi_comm_set_attr_ptr)(MPIABI_Fint *comm, MPIABI_Fint *comm_keyval, void *attribute_val, MPIABI_Fint *ierror);
void (*mpiabi_comm_set_info_ptr)(MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_comm_set_name_ptr)(MPIABI_Fint *comm, const char *comm_name, MPIABI_Fint *ierror);
void (*mpiabi_comm_size_ptr)(MPIABI_Fint *comm, MPIABI_Fint *size, MPIABI_Fint *ierror);
void (*mpiabi_comm_split_ptr)(MPIABI_Fint *comm, MPIABI_Fint *color, MPIABI_Fint *key, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_group_free_ptr)(MPIABI_Fint *group, MPIABI_Fint *ierror);
void (*mpiabi_comm_split_type_ptr)(MPIABI_Fint *comm, MPIABI_Fint *split_type, MPIABI_Fint *key, MPIABI_Fint *info, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_test_inter_ptr)(MPIABI_Fint *comm, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_group_compare_ptr)(MPIABI_Fint *group1, MPIABI_Fint *group2, MPIABI_Fint *result, MPIABI_Fint *ierror);
void (*mpiabi_group_difference_ptr)(MPIABI_Fint *group1, MPIABI_Fint *group2, MPIABI_Fint *newgroup, MPIABI_Fint *ierror);
void (*mpiabi_group_excl_ptr)(MPIABI_Fint *group, MPIABI_Fint *n, const MPIABI_Fint *ranks[], MPIABI_Fint *newgroup, MPIABI_Fint *ierror);
void (*mpiabi_group_from_session_pset_ptr)(MPIABI_Fint *session, const char *pset_name, MPIABI_Fint *newgroup, MPIABI_Fint *ierror);
void (*mpiabi_group_incl_ptr)(MPIABI_Fint *group, MPIABI_Fint *n, const MPIABI_Fint *ranks[], MPIABI_Fint *newgroup, MPIABI_Fint *ierror);
void (*mpiabi_group_intersection_ptr)(MPIABI_Fint *group1, MPIABI_Fint *group2, MPIABI_Fint *newgroup, MPIABI_Fint *ierror);
void (*mpiabi_group_range_excl_ptr)(MPIABI_Fint *group, MPIABI_Fint *n, MPIABI_Fint *ranges[][3], MPIABI_Fint *newgroup, MPIABI_Fint *ierror);
void (*mpiabi_group_range_incl_ptr)(MPIABI_Fint *group, MPIABI_Fint *n, MPIABI_Fint *ranges[][3], MPIABI_Fint *newgroup, MPIABI_Fint *ierror);
void (*mpiabi_group_rank_ptr)(MPIABI_Fint *group, MPIABI_Fint *rank, MPIABI_Fint *ierror);
void (*mpiabi_group_size_ptr)(MPIABI_Fint *group, MPIABI_Fint *size, MPIABI_Fint *ierror);
void (*mpiabi_group_translate_ranks_ptr)(MPIABI_Fint *group1, MPIABI_Fint *n, const MPIABI_Fint *ranks1[], MPIABI_Fint *group2, MPIABI_Fint *ranks2[], MPIABI_Fint *ierror);
void (*mpiabi_group_union_ptr)(MPIABI_Fint *group1, MPIABI_Fint *group2, MPIABI_Fint *newgroup, MPIABI_Fint *ierror);
void (*mpiabi_intercomm_create_ptr)(MPIABI_Fint *local_comm, MPIABI_Fint *local_leader, MPIABI_Fint *peer_comm, MPIABI_Fint *remote_leader, MPIABI_Fint *tag, MPIABI_Fint *newintercomm, MPIABI_Fint *ierror);
void (*mpiabi_intercomm_create_from_groups_ptr)( MPIABI_Fint *local_group, MPIABI_Fint *local_leader, MPIABI_Fint *remote_group, MPIABI_Fint *remote_leader, const char *stringtag, MPIABI_Fint *info, MPI_Fint *errhandler, MPIABI_Fint *newintercomm, MPIABI_Fint *ierror);
void (*mpiabi_intercomm_merge_ptr)(MPIABI_Fint *intercomm, MPIABI_Fint *high, MPIABI_Fint *newintracomm, MPIABI_Fint *ierror);
void (*mpiabi_type_create_keyval_ptr)(void (*type_copy_attr_fn)(void), void (*type_delete_attr_fn)(void), MPIABI_Fint *type_keyval, void *extra_state, MPIABI_Fint *ierror);
void (*mpiabi_type_delete_attr_ptr)(MPIABI_Fint *datatype, MPIABI_Fint *type_keyval, MPIABI_Fint *ierror);
void (*mpiabi_type_free_keyval_ptr)(MPIABI_Fint *type_keyval, MPIABI_Fint *ierror);
void (*mpiabi_type_get_attr_ptr)(MPIABI_Fint *datatype, MPIABI_Fint *type_keyval, void *attribute_val, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_type_get_name_ptr)(MPIABI_Fint *datatype, char *type_name, MPIABI_Fint *resultlen, MPIABI_Fint *ierror);
void (*mpiabi_type_set_attr_ptr)(MPIABI_Fint *datatype, MPIABI_Fint *type_keyval, void *attribute_val, MPIABI_Fint *ierror);
void (*mpiabi_type_set_name_ptr)(MPIABI_Fint *datatype, const char *type_name, MPIABI_Fint *ierror);
void (*mpiabi_win_create_keyval_ptr)(void (*win_copy_attr_fn)(void), void (*win_delete_attr_fn)(void), MPIABI_Fint *win_keyval, void *extra_state, MPIABI_Fint *ierror);
void (*mpiabi_win_delete_attr_ptr)(MPIABI_Fint *win, MPIABI_Fint *win_keyval, MPIABI_Fint *ierror);
void (*mpiabi_win_free_keyval_ptr)(MPIABI_Fint *win_keyval, MPIABI_Fint *ierror);
void (*mpiabi_win_get_attr_ptr)(MPIABI_Fint *win, MPIABI_Fint *win_keyval, void *attribute_val, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_win_get_name_ptr)(MPIABI_Fint *win, char *win_name, MPIABI_Fint *resultlen, MPIABI_Fint *ierror);
void (*mpiabi_win_set_attr_ptr)(MPIABI_Fint *win, MPIABI_Fint *win_keyval, void *attribute_val, MPIABI_Fint *ierror);
void (*mpiabi_win_set_name_ptr)(MPIABI_Fint *win, const char *win_name, MPIABI_Fint *ierror);

// A.3.6 Virtual Topologies for MPI Processes C Bindings

void (*mpiabi_cart_coords_ptr)(MPIABI_Fint *comm, MPIABI_Fint *rank, MPIABI_Fint *maxdims, MPIABI_Fint *coords[], MPIABI_Fint *ierror);
void (*mpiabi_cart_create_ptr)(MPIABI_Fint *comm_old, MPIABI_Fint *ndims, const MPIABI_Fint *dims[], const MPIABI_Fint *periods[], MPIABI_Fint *reorder, MPIABI_Fint *comm_cart, MPIABI_Fint *ierror);
void (*mpiabi_cart_get_ptr)(MPIABI_Fint *comm, MPIABI_Fint *maxdims, MPIABI_Fint *dims[], MPIABI_Fint *periods[], MPIABI_Fint *coords[], MPIABI_Fint *ierror);
void (*mpiabi_cart_map_ptr)(MPIABI_Fint *comm, MPIABI_Fint *ndims, const MPIABI_Fint *dims[], const MPIABI_Fint *periods[], MPIABI_Fint *newrank, MPIABI_Fint *ierror);
void (*mpiabi_cart_rank_ptr)(MPIABI_Fint *comm, const MPIABI_Fint *coords[], MPIABI_Fint *rank, MPIABI_Fint *ierror);
void (*mpiabi_cart_shift_ptr)(MPIABI_Fint *comm, MPIABI_Fint *direction, MPIABI_Fint *disp, MPIABI_Fint *rank_source, MPIABI_Fint *rank_dest, MPIABI_Fint *ierror);
void (*mpiabi_cart_sub_ptr)(MPIABI_Fint *comm, const MPIABI_Fint *remain_dims[], MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_cartdim_get_ptr)(MPIABI_Fint *comm, MPIABI_Fint *ndims, MPIABI_Fint *ierror);
void (*mpiabi_dims_create_ptr)(MPIABI_Fint *nnodes, MPIABI_Fint *ndims, MPIABI_Fint *dims[], MPIABI_Fint *ierror);
void (*mpiabi_dist_graph_create_ptr)( MPIABI_Fint *comm_old, MPIABI_Fint *n, const MPIABI_Fint *sources[], const MPIABI_Fint *degrees[], const MPIABI_Fint *destinations[], const MPIABI_Fint *weights[], MPIABI_Fint *info, MPIABI_Fint *reorder, MPIABI_Fint *comm_dist_graph, MPIABI_Fint *ierror);
void (*mpiabi_dist_graph_create_adjacent_ptr)( MPIABI_Fint *comm_old, MPIABI_Fint *indegree, const MPIABI_Fint *sources[], const MPIABI_Fint *sourceweights[], MPIABI_Fint *outdegree, const MPIABI_Fint *destinations[], const MPIABI_Fint *destweights[], MPIABI_Fint *info, MPIABI_Fint *reorder, MPIABI_Fint *comm_dist_graph, MPIABI_Fint *ierror);
void (*mpiabi_dist_graph_neighbors_ptr)( MPIABI_Fint *comm, MPIABI_Fint *maxindegree, MPIABI_Fint *sources[], MPIABI_Fint *sourceweights[], MPIABI_Fint *maxoutdegree, MPIABI_Fint *destinations[], MPIABI_Fint *destweights[], MPIABI_Fint *ierror);
void (*mpiabi_dist_graph_neighbors_count_ptr)(MPIABI_Fint *comm, MPIABI_Fint *indegree, MPIABI_Fint *outdegree, MPIABI_Fint *weighted, MPIABI_Fint *ierror);
void (*mpiabi_graph_create_ptr)(MPIABI_Fint *comm_old, MPIABI_Fint *nnodes, const MPIABI_Fint *index[], const MPIABI_Fint *edges[], MPIABI_Fint *reorder, MPIABI_Fint *comm_graph, MPIABI_Fint *ierror);
void (*mpiabi_graph_get_ptr)(MPIABI_Fint *comm, MPIABI_Fint *maxindex, MPIABI_Fint *maxedges, MPIABI_Fint *index[], MPIABI_Fint *edges[], MPIABI_Fint *ierror);
void (*mpiabi_graph_map_ptr)(MPIABI_Fint *comm, MPIABI_Fint *nnodes, const MPIABI_Fint *index[], const MPIABI_Fint *edges[], MPIABI_Fint *newrank, MPIABI_Fint *ierror);
void (*mpiabi_graph_neighbors_ptr)(MPIABI_Fint *comm, MPIABI_Fint *rank, MPIABI_Fint *maxneighbors, MPIABI_Fint *neighbors[], MPIABI_Fint *ierror);
void (*mpiabi_graph_neighbors_count_ptr)(MPIABI_Fint *comm, MPIABI_Fint *rank, MPIABI_Fint *nneighbors, MPIABI_Fint *ierror);
void (*mpiabi_graphdims_get_ptr)(MPIABI_Fint *comm, MPIABI_Fint *nnodes, MPIABI_Fint *nedges, MPIABI_Fint *ierror);
void (*mpiabi_ineighbor_allgather_ptr)( const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ineighbor_allgather_c_ptr)( const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ineighbor_allgatherv_ptr)( const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ineighbor_allgatherv_c_ptr)( const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ineighbor_alltoall_ptr)( const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ineighbor_alltoall_c_ptr)( const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ineighbor_alltoallv_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ineighbor_alltoallv_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_ineighbor_alltoallw_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_ineighbor_alltoallw_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_allgather_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_allgather_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_allgather_init_ptr)( const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_allgather_init_c_ptr)( const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_allgatherv_ptr)( const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_allgatherv_c_ptr)( const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_allgatherv_init_ptr)( const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_allgatherv_init_c_ptr)( const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *displs[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_alltoall_ptr)(const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_alltoall_c_ptr)(const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_alltoall_init_ptr)( const void *sendbuf, MPIABI_Fint *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Fint *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_alltoall_init_c_ptr)( const void *sendbuf, MPIABI_Count *sendcount, MPIABI_Fint *sendtype, void *recvbuf, MPIABI_Count *recvcount, MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_alltoallv_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_alltoallv_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_alltoallv_init_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Fint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Fint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_alltoallv_init_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], MPIABI_Fint *sendtype, void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], MPIABI_Fint *recvtype, MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_alltoallw_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_alltoallw_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_neighbor_alltoallw_init_ptr)( const void *sendbuf, const MPIABI_Fint *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Fint *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_neighbor_alltoallw_init_c_ptr)( const void *sendbuf, const MPIABI_Count *sendcounts[], const MPIABI_Aint *sdispls[], const MPIABI_Fint *sendtypes[], void *recvbuf, const MPIABI_Count *recvcounts[], const MPIABI_Aint *rdispls[], const MPIABI_Fint *recvtypes[], MPIABI_Fint *comm, MPIABI_Fint *info, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_topo_test_ptr)(MPIABI_Fint *comm, MPIABI_Fint *status, MPIABI_Fint *ierror);

// A.3.7 MPI Environmental Management C Bindings

void (*mpiabi_add_error_class_ptr)(MPIABI_Fint *errorclass, MPIABI_Fint *ierror);
void (*mpiabi_add_error_code_ptr)(MPIABI_Fint *errorclass, MPIABI_Fint *errorcode, MPIABI_Fint *ierror);
void (*mpiabi_add_error_string_ptr)(MPIABI_Fint *errorcode, const char *string, MPIABI_Fint *ierror);
void (*mpiabi_alloc_mem_ptr)(MPIABI_Aint *size, MPIABI_Fint *info, void *baseptr, MPIABI_Fint *ierror);
void (*mpiabi_comm_call_errhandler_ptr)(MPIABI_Fint *comm, MPIABI_Fint *errorcode, MPIABI_Fint *ierror);
void (*mpiabi_comm_create_errhandler_ptr)(void (*comm_errhandler_fn)(void), MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_comm_get_errhandler_ptr)(MPIABI_Fint *comm, MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_comm_set_errhandler_ptr)(MPIABI_Fint *comm, MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_errhandler_free_ptr)(MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_error_class_ptr)(MPIABI_Fint *errorcode, MPIABI_Fint *errorclass, MPIABI_Fint *ierror);
void (*mpiabi_error_string_ptr)(MPIABI_Fint *errorcode, char *string, MPIABI_Fint *resultlen, MPIABI_Fint *ierror);
void (*mpiabi_file_call_errhandler_ptr)(MPIABI_Fint *fh, MPIABI_Fint *errorcode, MPIABI_Fint *ierror);
void (*mpiabi_file_create_errhandler_ptr)(void (*file_errhandler_fn)(void), MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_file_get_errhandler_ptr)(MPIABI_Fint *file, MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_file_set_errhandler_ptr)(MPIABI_Fint *file, MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_free_mem_ptr)(void *base, MPIABI_Fint *ierror);
void (*mpiabi_get_hw_resource_info_ptr)(MPIABI_Fint *hw_info, MPIABI_Fint *ierror);
void (*mpiabi_get_library_version_ptr)(char *version, MPIABI_Fint *resultlen, MPIABI_Fint *ierror);
void (*mpiabi_get_processor_name_ptr)(char *name, MPIABI_Fint *resultlen, MPIABI_Fint *ierror);
void (*mpiabi_get_version_ptr)(MPIABI_Fint *version, MPIABI_Fint *subversion, MPIABI_Fint *ierror);
void (*mpiabi_remove_error_class_ptr)(MPIABI_Fint *errorclass, MPIABI_Fint *ierror);
void (*mpiabi_remove_error_code_ptr)(MPIABI_Fint *errorcode, MPIABI_Fint *ierror);
void (*mpiabi_remove_error_string_ptr)(MPIABI_Fint *errorcode, MPIABI_Fint *ierror);
void (*mpiabi_session_call_errhandler_ptr)(MPIABI_Fint *session, MPIABI_Fint *errorcode, MPIABI_Fint *ierror);
void (*mpiabi_session_create_errhandler_ptr)( void (*session_errhandler_fn)(void), MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_session_get_errhandler_ptr)(MPIABI_Fint *session, MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_session_set_errhandler_ptr)(MPIABI_Fint *session, MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_win_call_errhandler_ptr)(MPIABI_Fint *win, MPIABI_Fint *errorcode, MPIABI_Fint *ierror);
void (*mpiabi_win_create_errhandler_ptr)(void (*win_errhandler_fn)(void), MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_win_get_errhandler_ptr)(MPIABI_Fint *win, MPI_Fint *errhandler, MPIABI_Fint *ierror);
void (*mpiabi_win_set_errhandler_ptr)(MPIABI_Fint *win, MPI_Fint *errhandler, MPIABI_Fint *ierror);
double (*mpiabi_wtick_ptr)(void);
double (*mpiabi_wtime_ptr)(void);

// A.3.8 The Info Object C Bindings

void (*mpiabi_info_create_ptr)(MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_info_create_env_ptr)(MPIABI_Fint *argc, char *argv[], MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_info_delete_ptr)(MPIABI_Fint *info, const char *key, MPIABI_Fint *ierror);
void (*mpiabi_info_dup_ptr)(MPIABI_Fint *info, MPIABI_Fint *newinfo, MPIABI_Fint *ierror);
void (*mpiabi_info_free_ptr)(MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_info_get_nkeys_ptr)(MPIABI_Fint *info, MPIABI_Fint *nkeys, MPIABI_Fint *ierror);
void (*mpiabi_info_get_nthkey_ptr)(MPIABI_Fint *info, MPIABI_Fint *n, char *key, MPIABI_Fint *ierror);
void (*mpiabi_info_get_string_ptr)(MPIABI_Fint *info, const char *key, MPIABI_Fint *buflen, char *value, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_info_set_ptr)(MPIABI_Fint *info, const char *key, const char *value, MPIABI_Fint *ierror);

// A.3.9 Process Creation and Management C Bindings

void (*mpiabi_abort_ptr)(MPIABI_Fint *comm, MPIABI_Fint *errorcode, MPIABI_Fint *ierror);
void (*mpiabi_close_port_ptr)(const char *port_name, MPIABI_Fint *ierror);
void (*mpiabi_comm_accept_ptr)(const char *port_name, MPIABI_Fint *info, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_connect_ptr)(const char *port_name, MPIABI_Fint *info, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *newcomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_disconnect_ptr)(MPIABI_Fint *comm, MPIABI_Fint *ierror);
void (*mpiabi_comm_get_parent_ptr)(MPIABI_Fint *parent, MPIABI_Fint *ierror);
void (*mpiabi_comm_join_ptr)(MPIABI_Fint *fd, MPIABI_Fint *intercomm, MPIABI_Fint *ierror);
void (*mpiabi_comm_spawn_ptr)(const char *command, char *argv[], MPIABI_Fint *maxprocs, MPIABI_Fint *info, MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *intercomm, MPIABI_Fint *array_of_errcodes[], MPIABI_Fint *ierror);
void (*mpiabi_comm_spawn_multiple_ptr)( MPIABI_Fint *count, char *array_of_commands[], char *array_of_argv[], const MPIABI_Fint *array_of_maxprocs[], const MPIABI_Fint *array_of_info[], MPIABI_Fint *root, MPIABI_Fint *comm, MPIABI_Fint *intercomm, MPIABI_Fint *array_of_errcodes[], MPIABI_Fint *ierror);
void (*mpiabi_finalize_ptr)(MPIABI_Fint *ierror);
void (*mpiabi_finalized_ptr)(MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_init_ptr)(MPIABI_Fint *ierror);
void (*mpiabi_init_thread_ptr)(MPIABI_Fint *required, MPIABI_Fint *provided, MPIABI_Fint *ierror);
void (*mpiabi_initialized_ptr)(MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_is_thread_main_ptr)(MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_lookup_name_ptr)(const char *service_name, MPIABI_Fint *info, char *port_name, MPIABI_Fint *ierror);
void (*mpiabi_open_port_ptr)(MPIABI_Fint *info, char *port_name, MPIABI_Fint *ierror);
void (*mpiabi_publish_name_ptr)(const char *service_name, MPIABI_Fint *info, const char *port_name, MPIABI_Fint *ierror);
void (*mpiabi_query_thread_ptr)(MPIABI_Fint *provided, MPIABI_Fint *ierror);
void (*mpiabi_session_finalize_ptr)(MPIABI_Fint *session, MPIABI_Fint *ierror);
void (*mpiabi_session_get_info_ptr)(MPIABI_Fint *session, MPIABI_Fint *info_used, MPIABI_Fint *ierror);
void (*mpiabi_session_get_nth_pset_ptr)(MPIABI_Fint *session, MPIABI_Fint *info, MPIABI_Fint *n, MPIABI_Fint *pset_len, char *pset_name, MPIABI_Fint *ierror);
void (*mpiabi_session_get_num_psets_ptr)(MPIABI_Fint *session, MPIABI_Fint *info, MPIABI_Fint *npset_names, MPIABI_Fint *ierror);
void (*mpiabi_session_get_pset_info_ptr)(MPIABI_Fint *session, const char *pset_name, MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_session_init_ptr)(MPIABI_Fint *info, MPI_Fint *errhandler, MPIABI_Fint *session, MPIABI_Fint *ierror);
void (*mpiabi_unpublish_name_ptr)(const char *service_name, MPIABI_Fint *info, const char *port_name, MPIABI_Fint *ierror);

// A.3.10 One-Sided Communications C Bindings

void (*mpiabi_accumulate_ptr)(const void *origin_addr, MPIABI_Fint *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *ierror);
// void (*mpiabi_accumulate_c_ptr)(const void *origin_addr, MPIABI_Count *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Count *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_compare_and_swap_ptr)(const void *origin_addr, const void *compare_addr, void *result_addr, MPIABI_Fint *datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_fetch_and_op_ptr)(const void *origin_addr, void *result_addr, MPIABI_Fint *datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_get_ptr)(void *origin_addr, MPIABI_Fint *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_get_accumulate_ptr)( const void *origin_addr, MPIABI_Fint *origin_count, MPIABI_Fint *origin_datatype, void *result_addr, MPIABI_Fint *result_count, MPIABI_Fint *result_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *ierror);
// void (*mpiabi_get_accumulate_c_ptr)( const void *origin_addr, MPIABI_Count *origin_count, MPIABI_Fint *origin_datatype, void *result_addr, MPIABI_Count *result_count, MPIABI_Fint *result_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Count *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *ierror);
// void (*mpiabi_get_c_ptr)(void *origin_addr, MPIABI_Count *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Count *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_put_ptr)(const void *origin_addr, MPIABI_Fint *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *win, MPIABI_Fint *ierror);
// void (*mpiabi_put_c_ptr)(const void *origin_addr, MPIABI_Count *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Count *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_raccumulate_ptr)( const void *origin_addr, MPIABI_Fint *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_raccumulate_c_ptr)( const void *origin_addr, MPIABI_Count *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Count *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_rget_ptr)(void *origin_addr, MPIABI_Fint *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *win, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_rget_accumulate_ptr)( const void *origin_addr, MPIABI_Fint *origin_count, MPIABI_Fint *origin_datatype, void *result_addr, MPIABI_Fint *result_count, MPIABI_Fint *result_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_rget_accumulate_c_ptr)( const void *origin_addr, MPIABI_Count *origin_count, MPIABI_Fint *origin_datatype, void *result_addr, MPIABI_Count *result_count, MPIABI_Fint *result_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Count *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *op, MPIABI_Fint *win, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_rget_c_ptr)(void *origin_addr, MPIABI_Count *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Count *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *win, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_rput_ptr)(const void *origin_addr, MPIABI_Fint *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Fint *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *win, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_rput_c_ptr)(const void *origin_addr, MPIABI_Count *origin_count, MPIABI_Fint *origin_datatype, MPIABI_Fint *target_rank, MPIABI_Aint *target_disp, MPIABI_Count *target_count, MPIABI_Fint *target_datatype, MPIABI_Fint *win, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_win_allocate_ptr)(MPIABI_Aint *size, MPIABI_Fint *disp_unit, MPIABI_Fint *info, MPIABI_Fint *comm, void *baseptr, MPIABI_Fint *win, MPIABI_Fint *ierror);
// void (*mpiabi_win_allocate_c_ptr)(MPIABI_Aint *size, MPIABI_Aint *disp_unit, MPIABI_Fint *info, MPIABI_Fint *comm, void *baseptr, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_allocate_shared_ptr)(MPIABI_Aint *size, MPIABI_Fint *disp_unit, MPIABI_Fint *info, MPIABI_Fint *comm, void *baseptr, MPIABI_Fint *win, MPIABI_Fint *ierror);
// void (*mpiabi_win_allocate_shared_c_ptr)(MPIABI_Aint *size, MPIABI_Aint *disp_unit, MPIABI_Fint *info, MPIABI_Fint *comm, void *baseptr, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_attach_ptr)(MPIABI_Fint *win, void *base, MPIABI_Aint *size, MPIABI_Fint *ierror);
void (*mpiabi_win_complete_ptr)(MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_create_ptr)(void *base, MPIABI_Aint *size, MPIABI_Fint *disp_unit, MPIABI_Fint *info, MPIABI_Fint *comm, MPIABI_Fint *win, MPIABI_Fint *ierror);
// void (*mpiabi_win_create_c_ptr)(void *base, MPIABI_Aint *size, MPIABI_Aint *disp_unit, MPIABI_Fint *info, MPIABI_Fint *comm, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_create_dynamic_ptr)(MPIABI_Fint *info, MPIABI_Fint *comm, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_detach_ptr)(MPIABI_Fint *win, const void *base, MPIABI_Fint *ierror);
void (*mpiabi_win_fence_ptr)(MPIABI_Fint *assert, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_flush_ptr)(MPIABI_Fint *rank, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_flush_all_ptr)(MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_flush_local_ptr)(MPIABI_Fint *rank, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_flush_local_all_ptr)(MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_free_ptr)(MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_get_group_ptr)(MPIABI_Fint *win, MPIABI_Fint *group, MPIABI_Fint *ierror);
void (*mpiabi_win_get_info_ptr)(MPIABI_Fint *win, MPIABI_Fint *info_used, MPIABI_Fint *ierror);
void (*mpiabi_win_lock_ptr)(MPIABI_Fint *lock_type, MPIABI_Fint *rank, MPIABI_Fint *assert, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_lock_all_ptr)(MPIABI_Fint *assert, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_post_ptr)(MPIABI_Fint *group, MPIABI_Fint *assert, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_set_info_ptr)(MPIABI_Fint *win, MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_win_shared_query_ptr)(MPIABI_Fint *win, MPIABI_Fint *rank, MPIABI_Aint *size, MPIABI_Fint *disp_unit, void *baseptr, MPIABI_Fint *ierror);
// void (*mpiabi_win_shared_query_c_ptr)(MPIABI_Fint *win, MPIABI_Fint *rank, MPIABI_Aint *size, MPIABI_Aint *disp_unit, void *baseptr, MPIABI_Fint *ierror);
void (*mpiabi_win_start_ptr)(MPIABI_Fint *group, MPIABI_Fint *assert, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_sync_ptr)(MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_test_ptr)(MPIABI_Fint *win, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_win_unlock_ptr)(MPIABI_Fint *rank, MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_unlock_all_ptr)(MPIABI_Fint *win, MPIABI_Fint *ierror);
void (*mpiabi_win_wait_ptr)(MPIABI_Fint *win, MPIABI_Fint *ierror);

// A.3.11 al Interfaces C Bindings

void (*mpiabi_grequest_complete_ptr)(MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_grequest_start_ptr)(void (*query_fn)(void), void (*free_fn)(void), void (*cancel_fn)(void), void *extra_state, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_status_set_cancelled_ptr)(MPIABI_Fint *status, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_status_set_elements_ptr)(MPIABI_Fint *status, MPIABI_Fint *datatype, MPIABI_Fint *count, MPIABI_Fint *ierror);
// void (*mpiabi_status_set_elements_c_ptr)(MPIABI_Fint *status, MPIABI_Fint *datatype, MPIABI_Count *count, MPIABI_Fint *ierror);
void (*mpiabi_status_set_error_ptr)(MPIABI_Fint *status, MPIABI_Fint *err, MPIABI_Fint *ierror);
void (*mpiabi_status_set_source_ptr)(MPIABI_Fint *status, MPIABI_Fint *source, MPIABI_Fint *ierror);
void (*mpiabi_status_set_tag_ptr)(MPIABI_Fint *status, MPIABI_Fint *tag, MPIABI_Fint *ierror);

// A.3.12 I/O C Bindings

void (*mpiabi_file_close_ptr)(MPIABI_Fint *fh, MPIABI_Fint *ierror);
void (*mpiabi_file_delete_ptr)(const char *filename, MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_file_get_amode_ptr)(MPIABI_Fint *fh, MPIABI_Fint *amode, MPIABI_Fint *ierror);
void (*mpiabi_file_get_atomicity_ptr)(MPIABI_Fint *fh, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_file_get_byte_offset_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, MPIABI_Offset *disp, MPIABI_Fint *ierror);
void (*mpiabi_file_get_group_ptr)(MPIABI_Fint *fh, MPIABI_Fint *group, MPIABI_Fint *ierror);
void (*mpiabi_file_get_info_ptr)(MPIABI_Fint *fh, MPIABI_Fint *info_used, MPIABI_Fint *ierror);
void (*mpiabi_file_get_position_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, MPIABI_Fint *ierror);
void (*mpiabi_file_get_position_shared_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, MPIABI_Fint *ierror);
void (*mpiabi_file_get_size_ptr)(MPIABI_Fint *fh, MPIABI_Offset *size, MPIABI_Fint *ierror);
void (*mpiabi_file_get_type_extent_ptr)(MPIABI_Fint *fh, MPIABI_Fint *datatype, MPIABI_Aint *extent, MPIABI_Fint *ierror);
// void (*mpiabi_file_get_type_extent_c_ptr)(MPIABI_Fint *fh, MPIABI_Fint *datatype, MPIABI_Count *extent, MPIABI_Fint *ierror);
void (*mpiabi_file_get_view_ptr)(MPIABI_Fint *fh, MPIABI_Offset *disp, MPIABI_Fint *etype, MPIABI_Fint *filetype, char *datarep, MPIABI_Fint *ierror);
void (*mpiabi_file_iread_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iread_all_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iread_all_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iread_at_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iread_at_all_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iread_at_all_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iread_at_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iread_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iread_shared_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iread_shared_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iwrite_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iwrite_all_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iwrite_all_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iwrite_at_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iwrite_at_all_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iwrite_at_all_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iwrite_at_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iwrite_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_iwrite_shared_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
// void (*mpiabi_file_iwrite_shared_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *request, MPIABI_Fint *ierror);
void (*mpiabi_file_open_ptr)(MPIABI_Fint *comm, const char *filename, MPIABI_Fint *amode, MPIABI_Fint *info, MPIABI_Fint *fh, MPIABI_Fint *ierror);
void (*mpiabi_file_preallocate_ptr)(MPIABI_Fint *fh, MPIABI_Offset *size, MPIABI_Fint *ierror);
void (*mpiabi_file_read_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_all_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_all_begin_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_all_begin_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_all_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_all_end_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_at_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_at_all_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_at_all_begin_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_at_all_begin_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_at_all_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_at_all_end_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_at_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_ordered_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_ordered_begin_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_ordered_begin_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_ordered_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_ordered_end_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_read_shared_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_file_read_shared_c_ptr)(MPIABI_Fint *fh, void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_seek_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, MPIABI_Fint *whence, MPIABI_Fint *ierror);
void (*mpiabi_file_seek_shared_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, MPIABI_Fint *whence, MPIABI_Fint *ierror);
void (*mpiabi_file_set_atomicity_ptr)(MPIABI_Fint *fh, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_file_set_info_ptr)(MPIABI_Fint *fh, MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_file_set_size_ptr)(MPIABI_Fint *fh, MPIABI_Offset *size, MPIABI_Fint *ierror);
void (*mpiabi_file_set_view_ptr)(MPIABI_Fint *fh, MPIABI_Offset *disp, MPIABI_Fint *etype, MPIABI_Fint *filetype, const char *datarep, MPIABI_Fint *info, MPIABI_Fint *ierror);
void (*mpiabi_file_sync_ptr)(MPIABI_Fint *fh, MPIABI_Fint *ierror);
void (*mpiabi_file_write_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_all_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_all_begin_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_all_begin_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_all_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_all_end_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_at_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_at_all_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_at_all_begin_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_at_all_begin_c_ptr)( MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_at_all_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_at_all_end_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_at_c_ptr)(MPIABI_Fint *fh, MPIABI_Offset *offset, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_ordered_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_ordered_begin_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_ordered_begin_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_ordered_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_ordered_end_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_file_write_shared_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Fint *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
// void (*mpiabi_file_write_shared_c_ptr)(MPIABI_Fint *fh, const void *buf, MPIABI_Count *count, MPIABI_Fint *datatype, MPIABI_Fint *status, MPIABI_Fint *ierror);
void (*mpiabi_register_datarep_ptr)(const char *datarep, void (*read_conversion_fn)(void), void (*write_conversion_fn)(void), void (*dtype_file_extent_fn)(void), void *extra_state, MPIABI_Fint *ierror);
// void (*mpiabi_register_datarep_c_ptr)(const char *datarep, void (*read_conversion_fn)(void), void (*write_conversion_fn)(void), void (*dtype_file_extent_fn)(void), void *extra_state, MPIABI_Fint *ierror);

// A.3.13 Language Bindings C Bindings

// A.3.14 Tools / Profiling Interface C Bindings

void (*mpiabi_pcontrol_ptr)(const MPIABI_Fint *level, MPIABI_Fint *ierror);

// A.3.15 Tools / MPI Tool Information Interface C Bindings

// A.3.16 Deprecated C Bindings

void (*mpiabi_attr_delete_ptr)(MPIABI_Fint *comm, MPIABI_Fint *keyval, MPIABI_Fint *ierror);
void (*mpiabi_attr_get_ptr)(MPIABI_Fint *comm, MPIABI_Fint *keyval, void *attribute_val, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_attr_put_ptr)(MPIABI_Fint *comm, MPIABI_Fint *keyval, void *attribute_val, MPIABI_Fint *ierror);
void (*mpiabi_get_elements_x_ptr)(const MPIABI_Fint *status, MPIABI_Fint *datatype, MPIABI_Count *count, MPIABI_Fint *ierror);
void (*mpiabi_info_get_ptr)(MPIABI_Fint *info, const char *key, MPIABI_Fint *valuelen, char *value, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_info_get_valuelen_ptr)(MPIABI_Fint *info, const char *key, MPIABI_Fint *valuelen, MPIABI_Fint *flag, MPIABI_Fint *ierror);
void (*mpiabi_keyval_create_ptr)(void (*copy_fn)(void), void (*delete_fn)(void), MPIABI_Fint *keyval, void *extra_state, MPIABI_Fint *ierror);
void (*mpiabi_keyval_free_ptr)(MPIABI_Fint *keyval, MPIABI_Fint *ierror);
void (*mpiabi_status_set_elements_x_ptr)(MPIABI_Fint *status, MPIABI_Fint *datatype, MPIABI_Count *count, MPIABI_Fint *ierror);
void (*mpiabi_type_get_extent_x_ptr)(MPIABI_Fint *datatype, MPIABI_Count *lb, MPIABI_Count *extent, MPIABI_Fint *ierror);
void (*mpiabi_type_get_true_extent_x_ptr)(MPIABI_Fint *datatype, MPIABI_Count *true_lb, MPIABI_Count *true_extent, MPIABI_Fint *ierror);
void (*mpiabi_type_size_x_ptr)(MPIABI_Fint *datatype, MPIABI_Count *size, MPIABI_Fint *ierror);

// Removed C Bindings

void (*mpiabi_address_ptr)(void *location, MPIABI_Aint *address, MPIABI_Fint *ierror);
void (*mpiabi_type_hindexed_ptr)(MPIABI_Fint *count, MPIABI_Fint *array_of_blocklengths, MPIABI_Aint *array_of_displacements, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_hvector_ptr)(MPIABI_Fint *count, MPIABI_Fint *blocklength, MPIABI_Aint *stride, MPIABI_Fint *oldtype, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_struct_ptr)(MPIABI_Fint *count, MPIABI_Fint *array_of_blocklengths, MPIABI_Aint *array_of_displacements, MPIABI_Fint *array_of_types, MPIABI_Fint *newtype, MPIABI_Fint *ierror);
void (*mpiabi_type_extent_ptr)(MPIABI_Fint *datatype, MPIABI_Aint *extent, MPIABI_Fint *ierror);
void (*mpiabi_type_lb_ptr)(MPIABI_Fint *datatype, MPIABI_Aint *displacement, MPIABI_Fint *ierror);
void (*mpiabi_type_ub_ptr)(MPIABI_Fint *datatype, MPIABI_Aint *displacement, MPIABI_Fint *ierror);
