      integer MPITRAMPOLINE_VERSION_MAJOR
      integer MPITRAMPOLINE_VERSION_MINOR
      integer MPITRAMPOLINE_VERSION_PATCH
      parameter (MPITRAMPOLINE_VERSION_MAJOR = 6)
      parameter (MPITRAMPOLINE_VERSION_MINOR = 0)
      parameter (MPITRAMPOLINE_VERSION_PATCH = 0)
