constants_fortran = [
    ("MPI_Fint", "MPI_ANY_SOURCE"),
    ("MPI_Fint", "MPI_ANY_TAG"),
    ("MPI_Fint", "MPI_PROC_NULL"),
    ("MPI_Fint", "MPI_ROOT"),

    ("MPI_Fint", "MPI_CONGRUENT"),
    ("MPI_Fint", "MPI_IDENT"),
    ("MPI_Fint", "MPI_SIMILAR"),
    ("MPI_Fint", "MPI_UNEQUAL"),

    ("MPI_Fint", "MPI_ERROR"),
    ("MPI_Fint", "MPI_SOURCE"),
    ("MPI_Fint", "MPI_TAG"),

    ("MPI_Fint", "MPI_KEYVAL_INVALID"),
    ("MPI_Fint", "MPI_UNDEFINED"),

    ("MPI_Fint", "MPI_COMBINER_CONTIGUOUS"),
    ("MPI_Fint", "MPI_COMBINER_DARRAY"),
    ("MPI_Fint", "MPI_COMBINER_DUP"),
    ("MPI_Fint", "MPI_COMBINER_F90_COMPLEX"),
    ("MPI_Fint", "MPI_COMBINER_F90_INTEGER"),
    ("MPI_Fint", "MPI_COMBINER_F90_REAL"),
    ("MPI_Fint", "MPI_COMBINER_HINDEXED"),
    ("MPI_Fint", "MPI_COMBINER_HINDEXED_BLOCK"),
    # ("MPI_Fint", "MPI_COMBINER_HINDEXED_INTEGER"),
    ("MPI_Fint", "MPI_COMBINER_HVECTOR"),
    # ("MPI_Fint", "MPI_COMBINER_HVECTOR_INTEGER"),
    ("MPI_Fint", "MPI_COMBINER_INDEXED"),
    ("MPI_Fint", "MPI_COMBINER_INDEXED_BLOCK"),
    ("MPI_Fint", "MPI_COMBINER_NAMED"),
    ("MPI_Fint", "MPI_COMBINER_RESIZED"),
    ("MPI_Fint", "MPI_COMBINER_STRUCT"),
    # ("MPI_Fint", "MPI_COMBINER_STRUCT_INTEGER"),
    ("MPI_Fint", "MPI_COMBINER_SUBARRAY"),
    ("MPI_Fint", "MPI_COMBINER_VECTOR"),

    ("MPI_Fint", "MPI_DISTRIBUTE_BLOCK"),
    ("MPI_Fint", "MPI_DISTRIBUTE_CYCLIC"),
    ("MPI_Fint", "MPI_DISTRIBUTE_NONE"),

    ("MPI_Fint", "MPI_ERR_ACCESS"),
    ("MPI_Fint", "MPI_ERR_AMODE"),
    ("MPI_Fint", "MPI_ERR_ARG"),
    ("MPI_Fint", "MPI_ERR_ASSERT"),
    ("MPI_Fint", "MPI_ERR_BAD_FILE"),
    ("MPI_Fint", "MPI_ERR_BASE"),
    ("MPI_Fint", "MPI_ERR_BUFFER"),
    ("MPI_Fint", "MPI_ERR_COMM"),
    ("MPI_Fint", "MPI_ERR_CONVERSION"),
    ("MPI_Fint", "MPI_ERR_COUNT"),
    ("MPI_Fint", "MPI_ERR_DIMS"),
    ("MPI_Fint", "MPI_ERR_DISP"),
    ("MPI_Fint", "MPI_ERR_DUP_DATAREP"),
    ("MPI_Fint", "MPI_ERR_FILE"),
    ("MPI_Fint", "MPI_ERR_FILE_EXISTS"),
    ("MPI_Fint", "MPI_ERR_FILE_IN_USE"),
    ("MPI_Fint", "MPI_ERR_GROUP"),
    ("MPI_Fint", "MPI_ERR_INFO"),
    ("MPI_Fint", "MPI_ERR_INFO_KEY"),
    ("MPI_Fint", "MPI_ERR_INFO_NOKEY"),
    ("MPI_Fint", "MPI_ERR_INFO_VALUE"),
    ("MPI_Fint", "MPI_ERR_INTERN"),
    ("MPI_Fint", "MPI_ERR_IN_STATUS"),
    ("MPI_Fint", "MPI_ERR_IO"),
    ("MPI_Fint", "MPI_ERR_KEYVAL"),
    ("MPI_Fint", "MPI_ERR_LOCKTYPE"),
    ("MPI_Fint", "MPI_ERR_NAME"),
    ("MPI_Fint", "MPI_ERR_NOT_SAME"),
    ("MPI_Fint", "MPI_ERR_NO_MEM"),
    ("MPI_Fint", "MPI_ERR_NO_SPACE"),
    ("MPI_Fint", "MPI_ERR_NO_SUCH_FILE"),
    ("MPI_Fint", "MPI_ERR_OP"),
    ("MPI_Fint", "MPI_ERR_OTHER"),
    ("MPI_Fint", "MPI_ERR_PENDING"),
    ("MPI_Fint", "MPI_ERR_PORT"),
    ("MPI_Fint", "MPI_ERR_QUOTA"),
    ("MPI_Fint", "MPI_ERR_RANK"),
    ("MPI_Fint", "MPI_ERR_READ_ONLY"),
    ("MPI_Fint", "MPI_ERR_REQUEST"),
    ("MPI_Fint", "MPI_ERR_RMA_ATTACH"),
    ("MPI_Fint", "MPI_ERR_RMA_CONFLICT"),
    ("MPI_Fint", "MPI_ERR_RMA_FLAVOR"),
    ("MPI_Fint", "MPI_ERR_RMA_RANGE"),
    ("MPI_Fint", "MPI_ERR_RMA_SHARED"),
    ("MPI_Fint", "MPI_ERR_RMA_SYNC"),
    ("MPI_Fint", "MPI_ERR_ROOT"),
    ("MPI_Fint", "MPI_ERR_SERVICE"),
    ("MPI_Fint", "MPI_ERR_SIZE"),
    ("MPI_Fint", "MPI_ERR_SPAWN"),
    ("MPI_Fint", "MPI_ERR_TAG"),
    ("MPI_Fint", "MPI_ERR_TOPOLOGY"),
    ("MPI_Fint", "MPI_ERR_TRUNCATE"),
    ("MPI_Fint", "MPI_ERR_TYPE"),
    ("MPI_Fint", "MPI_ERR_UNKNOWN"),
    ("MPI_Fint", "MPI_ERR_UNSUPPORTED_DATAREP"),
    ("MPI_Fint", "MPI_ERR_UNSUPPORTED_OPERATION"),
    ("MPI_Fint", "MPI_ERR_WIN"),
    ("MPI_Fint", "MPI_SUCCESS"),

    ("MPI_Fint", "MPI_MODE_APPEND"),
    ("MPI_Fint", "MPI_MODE_CREATE"),
    ("MPI_Fint", "MPI_MODE_DELETE_ON_CLOSE"),
    ("MPI_Fint", "MPI_MODE_EXCL"),
    ("MPI_Fint", "MPI_MODE_RDONLY"),
    ("MPI_Fint", "MPI_MODE_RDWR"),
    ("MPI_Fint", "MPI_MODE_SEQUENTIAL"),
    ("MPI_Fint", "MPI_MODE_UNIQUE_OPEN"),
    ("MPI_Fint", "MPI_MODE_WRONLY"),

    ("MPI_Fint", "MPI_ORDER_C"),
    ("MPI_Fint", "MPI_ORDER_FORTRAN"),

    ("MPI_Fint", "MPI_THREAD_SINGLE"),
    ("MPI_Fint", "MPI_THREAD_FUNNELED"),
    ("MPI_Fint", "MPI_THREAD_SERIALIZED"),
    ("MPI_Fint", "MPI_THREAD_MULTIPLE"),

    ("MPI_Fint", "MPI_WIN_FLAVOR_ALLOCATE"),
    ("MPI_Fint", "MPI_WIN_FLAVOR_CREATE"),
    ("MPI_Fint", "MPI_WIN_FLAVOR_DYNAMIC"),
    ("MPI_Fint", "MPI_WIN_FLAVOR_SHARED"),
    ("MPI_Fint", "MPI_WIN_SEPARATE"),
    ("MPI_Fint", "MPI_WIN_UNIFIED"),

    # ("void *", "MPI_IN_PLACE"),

    ("MPI_Comm", "MPI_COMM_NULL"),
    ("MPI_Comm", "MPI_COMM_SELF"),
    ("MPI_Comm", "MPI_COMM_WORLD"),

    # ("MPI_Datatype", "MPI_2COMPLEX"),
    # ("MPI_Datatype", "MPI_2DOUBLE_COMPLEX"),
    ("MPI_Datatype", "MPI_2DOUBLE_PRECISION"),
    ("MPI_Datatype", "MPI_2INTEGER"),
    ("MPI_Datatype", "MPI_2REAL"),
    ("MPI_Datatype", "MPI_AINT"),
    ("MPI_Datatype", "MPI_BYTE"),
    ("MPI_Datatype", "MPI_CHAR"),
    ("MPI_Datatype", "MPI_CHARACTER"),
    ("MPI_Datatype", "MPI_COMPLEX"),
    ("MPI_Datatype", "MPI_COMPLEX16"),
    ("MPI_Datatype", "MPI_COMPLEX32"),
    # ("MPI_Datatype", "MPI_COMPLEX4"),
    ("MPI_Datatype", "MPI_COMPLEX8"),
    ("MPI_Datatype", "MPI_COUNT"),
    ("MPI_Datatype", "MPI_CXX_BOOL"),
    ("MPI_Datatype", "MPI_CXX_DOUBLE_COMPLEX"),
    ("MPI_Datatype", "MPI_CXX_FLOAT_COMPLEX"),
    ("MPI_Datatype", "MPI_CXX_LONG_DOUBLE_COMPLEX"),
    ("MPI_Datatype", "MPI_C_BOOL"),
    ("MPI_Datatype", "MPI_C_COMPLEX"),
    ("MPI_Datatype", "MPI_C_DOUBLE_COMPLEX"),
    ("MPI_Datatype", "MPI_C_FLOAT_COMPLEX"),
    ("MPI_Datatype", "MPI_C_LONG_DOUBLE_COMPLEX"),
    ("MPI_Datatype", "MPI_Datatype_NULL"),
    ("MPI_Datatype", "MPI_DOUBLE"),
    ("MPI_Datatype", "MPI_DOUBLE_COMPLEX"),
    ("MPI_Datatype", "MPI_DOUBLE_INT"),
    ("MPI_Datatype", "MPI_DOUBLE_PRECISION"),
    ("MPI_Datatype", "MPI_FLOAT"),
    ("MPI_Datatype", "MPI_FLOAT_INT"),
    ("MPI_Datatype", "MPI_INT"),
    ("MPI_Datatype", "MPI_INT16_T"),
    ("MPI_Datatype", "MPI_INT32_T"),
    ("MPI_Datatype", "MPI_INT64_T"),
    ("MPI_Datatype", "MPI_INT8_T"),
    ("MPI_Datatype", "MPI_INTEGER"),
    ("MPI_Datatype", "MPI_INTEGER1"),
    # ("MPI_Datatype", "MPI_INTEGER16"),
    ("MPI_Datatype", "MPI_INTEGER2"),
    ("MPI_Datatype", "MPI_INTEGER4"),
    ("MPI_Datatype", "MPI_INTEGER8"),
    # ("MPI_Datatype", "MPI_LB"),
    ("MPI_Datatype", "MPI_LOGICAL"),
    # ("MPI_Datatype", "MPI_LOGICAL1"),
    # ("MPI_Datatype", "MPI_LOGICAL2"),
    # ("MPI_Datatype", "MPI_LOGICAL4"),
    # ("MPI_Datatype", "MPI_LOGICAL8"),
    ("MPI_Datatype", "MPI_LONG"),
    ("MPI_Datatype", "MPI_LONG_DOUBLE"),
    ("MPI_Datatype", "MPI_LONG_DOUBLE_INT"),
    ("MPI_Datatype", "MPI_LONG_INT"),
    ("MPI_Datatype", "MPI_LONG_LONG"),
    ("MPI_Datatype", "MPI_LONG_LONG_INT"),
    ("MPI_Datatype", "MPI_OFFSET"),
    ("MPI_Datatype", "MPI_PACKED"),
    ("MPI_Datatype", "MPI_REAL"),
    ("MPI_Datatype", "MPI_REAL16"),
    # ("MPI_Datatype", "MPI_REAL2"),
    ("MPI_Datatype", "MPI_REAL4"),
    ("MPI_Datatype", "MPI_REAL8"),
    ("MPI_Datatype", "MPI_SHORT"),
    ("MPI_Datatype", "MPI_SHORT_INT"),
    ("MPI_Datatype", "MPI_SIGNED_CHAR"),
    # ("MPI_Datatype", "MPI_UB"),
    ("MPI_Datatype", "MPI_UINT16_T"),
    ("MPI_Datatype", "MPI_UINT32_T"),
    ("MPI_Datatype", "MPI_UINT64_T"),
    ("MPI_Datatype", "MPI_UINT8_T"),
    ("MPI_Datatype", "MPI_UNSIGNED"),
    ("MPI_Datatype", "MPI_UNSIGNED_CHAR"),
    ("MPI_Datatype", "MPI_UNSIGNED_LONG"),
    ("MPI_Datatype", "MPI_UNSIGNED_LONG_LONG"),
    ("MPI_Datatype", "MPI_UNSIGNED_SHORT"),
    ("MPI_Datatype", "MPI_WCHAR"),
]
