#ifndef MPIABI_VERSION_H
#define MPIABI_VERSION_H

#define MPIABI_VERSION_MAJOR 3
#define MPIABI_VERSION_MINOR 0
#define MPIABI_VERSION_PATCH 0

#define MPIABI_VERSION_H_INCLUDED
#endif // #ifndef MPIABI_VERSION_H
#ifndef MPIABI_VERSION_H_INCLUDED
#error
#endif
