name: CI-mpitrampoline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: |
        cd mpitrampoline
        cmake \
            -B ${{github.workspace}}/build \
            -DCMAKE_INSTALL_PREFIX=$HOME/mpitrampoline

    - name: Build
      run: cd mpitrampoline && cmake --build ${{github.workspace}}/build --verbose

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      run: cd mpitrampoline && cmake --install ${{github.workspace}}/build
