name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        fortran: [fortran-off, fortran-on]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        case $RUNNER_OS in
        Linux)
            case $${{matrix.fortran}} in
            fortran-off)
                cmake -B ${{github.workspace}}/build \
                    -DENABLE_FORTRAN=off \
                    -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                    -DCMAKE_INSTALL_PREFIX=$HOME/mpitrampoline
                ;;
            fortran-on)
                cmake -B ${{github.workspace}}/build \
                    -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                    -DCMAKE_INSTALL_PREFIX=$HOME/mpitrampoline
                ;;
            esac
            ;;
        macOS)
            # Use GCC-11 from Homebrew
            case $${{matrix.fortran}} in
            fortran-off)
                cmake -B ${{github.workspace}}/build \
                    -DENABLE_FORTRAN=off \
                    -DCMAKE_C_COMPILER=gcc-11 \
                    -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                    -DCMAKE_INSTALL_PREFIX=$HOME/mpitrampoline
                ;;
            fortran-on)
                cmake -B ${{github.workspace}}/build \
                    -DCMAKE_C_COMPILER=gcc-11 \
                    -DCMAKE_Fortran_COMPILER=gfortran-11 \
                    -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                    -DCMAKE_INSTALL_PREFIX=$HOME/mpitrampoline
                ;;
            esac
            ;;
        esac

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
