name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: shellcheck
      run: shellcheck bin/*
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        fortran: [fortran-off, fortran-on]
        shared: [shared-off, shared-on]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        fortran=$(echo ${{matrix.fortran}} | sed -e 's/fortran-//')
        shared=$(echo ${{matrix.shared}} | sed -e 's/shared-//')
        case $RUNNER_OS in
        Linux)
            cmake -B ${{github.workspace}}/build \
                -DENABLE_FORTRAN=${fortran} \
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                -DBUILD_SHARED_LIBS=${shared} \
                -DCMAKE_INSTALL_PREFIX=$HOME/mpitrampoline
            ;;
        macOS)
            # Use GCC-11 from Homebrew
            cmake -B ${{github.workspace}}/build \
                -DENABLE_FORTRAN=${fortran} \
                -DCMAKE_C_COMPILER=gcc-11 \
                -DCMAKE_CXX_COMPILER=g++-11 \
                -DCMAKE_Fortran_COMPILER=gfortran-11 \
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                -DBUILD_SHARED_LIBS=${shared} \
                -DCMAKE_INSTALL_PREFIX=$HOME/mpitrampoline
            ;;
        esac

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
